# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pushover
email: ebrodeur@ujami.net
baseurl: "/pushover" # the subpath of your site, e.g. /blog
url: "http://erniebrodeur.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

description: A gem to interface with pushover.net
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker